In [1]:
import numpy as np

In [2]:
pylist = [1,2,3,5,-5] #define a python list

In [3]:
pylist

[1, 2, 3, 5, -5]

In [4]:
np.array(pylist)     #create a 1-D numpy array

array([ 1,  2,  3,  5, -5])

In [5]:
np.array(pylist).shape   #get shape details of an array like no. of lists, no. of elements inside those lists

(5,)

In [6]:
len(np.array(pylist).shape)  

1

In [14]:
pyLoL = [[1,2,0], [3,4,5]]  #Python list of lists

In [15]:
np.array(pyLoL) #2-D numpy array

array([[1, 2, 0],
       [3, 4, 5]])

In [16]:
np.array(pyLoL).shape

(2, 3)

In [17]:
len(np.array(pyLoL).shape)

2

In [19]:
np.zeros((2,4,3))  #array with zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.random.randint(7)  #generate random integer

0

In [22]:
np.random.randint(5, size=(2,2)) #generate random list within defined shape and ineteger range

array([[1, 4],
       [0, 0]], dtype=int32)

In [25]:
arr = np.array(pylist, dtype = np.int64)  #assign custom datatype

In [26]:
arr.dtype

dtype('int64')

In [29]:
a = [1, 2, 4.5, 7.2]

In [30]:
float_arr = np.array(a)

In [32]:
float_arr

array([1. , 2. , 4.5, 7.2])

In [35]:
float_arr.astype(np.int32) #convert data type of array

array([1, 2, 4, 7], dtype=int32)