In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5, 5)

In [3]:
arr

array([[0.42324024, 0.67409315, 0.93290223, 0.60601314, 0.11075385],
       [0.38433457, 0.82733614, 0.37897615, 0.19475014, 0.86235845],
       [0.55616065, 0.41089851, 0.22867528, 0.01567323, 0.51721648],
       [0.4704557 , 0.92002937, 0.18305147, 0.26238963, 0.4666114 ],
       [0.20393779, 0.17799486, 0.39007551, 0.86010599, 0.21178207]])

In [4]:
arr.shape

(5, 5)

In [5]:
arr.dtype

dtype('float64')

In [10]:
arr[:4] #cut to 4th index of row i.e. 3.

array([[0.42324024, 0.67409315, 0.93290223, 0.60601314, 0.11075385],
       [0.38433457, 0.82733614, 0.37897615, 0.19475014, 0.86235845],
       [0.55616065, 0.41089851, 0.22867528, 0.01567323, 0.51721648],
       [0.4704557 , 0.92002937, 0.18305147, 0.26238963, 0.4666114 ]])

In [8]:
arr[:4].shape

(4, 5)

In [11]:
arr[:, :4] #cutting column

array([[0.42324024, 0.67409315, 0.93290223, 0.60601314],
       [0.38433457, 0.82733614, 0.37897615, 0.19475014],
       [0.55616065, 0.41089851, 0.22867528, 0.01567323],
       [0.4704557 , 0.92002937, 0.18305147, 0.26238963],
       [0.20393779, 0.17799486, 0.39007551, 0.86010599]])

In [13]:
arr[:-1] #cutting the last row

array([[0.42324024, 0.67409315, 0.93290223, 0.60601314, 0.11075385],
       [0.38433457, 0.82733614, 0.37897615, 0.19475014, 0.86235845],
       [0.55616065, 0.41089851, 0.22867528, 0.01567323, 0.51721648],
       [0.4704557 , 0.92002937, 0.18305147, 0.26238963, 0.4666114 ]])

In [14]:
inp_arr = np.random.randint(5, size=(7,8))

In [15]:
inp_arr

array([[3, 1, 0, 4, 0, 1, 2, 2],
       [0, 1, 4, 1, 3, 4, 1, 4],
       [1, 1, 3, 1, 2, 1, 0, 3],
       [1, 3, 3, 1, 2, 2, 0, 2],
       [0, 1, 4, 2, 1, 3, 3, 3],
       [2, 2, 0, 4, 4, 3, 1, 0],
       [0, 4, 0, 0, 1, 2, 3, 4]], dtype=int32)

In [16]:
ia0 = inp_arr[0]

In [17]:
ia0

array([3, 1, 0, 4, 0, 1, 2, 2], dtype=int32)

In [23]:
ia0_is012 = (ia0 == 0 )| (ia0 == 1) | (ia0 == 2) #detect specific values via Boolean validation

In [24]:
ia0_is012

array([False,  True,  True, False,  True,  True,  True,  True])

In [26]:
ia0[ia0_is012] #mask the array to obtain those specific values only

array([1, 0, 0, 1, 2, 2], dtype=int32)