In [2]:
import numpy as np

In [3]:
marks = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]  #marks of three students in four subjects

In [4]:
marks[0] #marks of student 1 in all subjects

[1, 2, 3, 4]

In [5]:
marks[0][0], marks[1][0], marks[2][0] #marks of all students in maths subject, long method

(1, 5, 9)

In [6]:
marks_transpose = []                                    #python loops to transpose
for j in range (len(marks[0])):
    marks_transpose.append([])
    for i in range (len(marks)):
        marks_transpose[j].append(marks[i][j])

In [7]:
marks_transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [8]:
marks_arr = np.array(marks)

In [9]:
marks_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
marks_tp = marks_arr.T                #transpose using numpy

In [11]:
marks_tp

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [12]:
(marks_arr.sum(axis=1)/60)*100                 #get percentage of each student

array([16.66666667, 43.33333333, 70.        ])

In [13]:
marks_tp.sum(axis=1)                           #class total marks scored in each subject (like 15 in maths)

array([15, 18, 21, 24])

In [14]:
#broadcasting

In [15]:
grace_marksErr1 = np.array([1,2,3])              #1-D array, Vector

In [16]:
grace_marksErr1.shape

(3,)

In [17]:
marks_arr + grace_marksErr1             #this will throw an error as we're trying to add shapes (3,4) and (3,)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [18]:
grace_marksErr2 = np.array([[1,2,3]])          #1x3 matrix 

In [19]:
grace_marksErr2.shape 

(1, 3)

In [20]:
marks_arr + grace_marksErr2          #this will throw an error as we're trying to add shapes (3,4) and (1,3)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [21]:
grace_marks = grace_marksErr2.T      #transpose the 1x3 matrix to get the usable 3x1 matrix

In [22]:
grace_marks

array([[1],
       [2],
       [3]])

In [23]:
grace_marks.shape

(3, 1)

In [24]:
marks_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
marks_arr + grace_marks

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [26]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [27]:
weightage = [[0.4], [0.2], [0.2], [0.2]]

In [28]:
multres = []                                                #looping for matrix multiplication
for i in range(len(marks)):
    multres.append([])
    for j in range(len(weightage[0])):
        curr_sum = 0 
        for k in range(len(marks[i])):
            curr_sum += marks[i][k]*weightage[k][j]
        multres[i].append(curr_sum)

In [29]:
multres

[[2.2], [6.200000000000001], [10.2]]

In [30]:
marks_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
wg = np.array(weightage)                                #weightage array

In [32]:
wg

array([[0.4],
       [0.2],
       [0.2],
       [0.2]])

In [37]:
marks_arr @ wg                                    #numpy operator for matrix multiplication

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2],[3]])