In [1]:
import numpy as np

In [2]:
marks = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]  #marks of three students in four subjects

In [3]:
marks[0] #marks of student 1 in all subjects

[1, 2, 3, 4]

In [8]:
marks[0][0], marks[1][0], marks[2][0] #marks of all students in maths subject, long method

(1, 5, 9)

In [10]:
marks_transpose = []                                    #python loops to transpose
for j in range (len(marks[0])):
    marks_transpose.append([])
    for i in range (len(marks)):
        marks_transpose[j].append(marks[i][j])

In [11]:
marks_transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [14]:
marks_arr = np.array(marks)

In [15]:
marks_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
marks_tp = marks_arr.T                #transpose using numpy

In [17]:
marks_tp

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [22]:
(marks_arr.sum(axis=1)/60)*100                 #get percentage of each student

array([16.66666667, 43.33333333, 70.        ])

In [23]:
marks_tp.sum(axis=1)                           #class total marks scored in each subject (like 15 in maths)

array([15, 18, 21, 24])